=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  # UTM attribution data
  class AnonymizedAttributionAttribution
    attr_accessor :utm_source

    attr_accessor :utm_campaign

    attr_accessor :utm_medium

    attr_accessor :utm_content

    # When the UTM link was clicked
    attr_accessor :clicked_at

    # Time from click to investment
    attr_accessor :time_to_invest_bucket

    # Attribution quality assessment
    attr_accessor :quality_score

    # Number of other UTM sources in the attribution window
    attr_accessor :competing_sources

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'utm_source' => :'utm_source',
        :'utm_campaign' => :'utm_campaign',
        :'utm_medium' => :'utm_medium',
        :'utm_content' => :'utm_content',
        :'clicked_at' => :'clicked_at',
        :'time_to_invest_bucket' => :'time_to_invest_bucket',
        :'quality_score' => :'quality_score',
        :'competing_sources' => :'competing_sources'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'utm_source' => :'String',
        :'utm_campaign' => :'String',
        :'utm_medium' => :'String',
        :'utm_content' => :'String',
        :'clicked_at' => :'Time',
        :'time_to_invest_bucket' => :'String',
        :'quality_score' => :'String',
        :'competing_sources' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'utm_medium',
        :'utm_content',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::AnonymizedAttributionAttribution` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::AnonymizedAttributionAttribution`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'utm_source')
        self.utm_source = attributes[:'utm_source']
      end

      if attributes.key?(:'utm_campaign')
        self.utm_campaign = attributes[:'utm_campaign']
      end

      if attributes.key?(:'utm_medium')
        self.utm_medium = attributes[:'utm_medium']
      end

      if attributes.key?(:'utm_content')
        self.utm_content = attributes[:'utm_content']
      end

      if attributes.key?(:'clicked_at')
        self.clicked_at = attributes[:'clicked_at']
      end

      if attributes.key?(:'time_to_invest_bucket')
        self.time_to_invest_bucket = attributes[:'time_to_invest_bucket']
      end

      if attributes.key?(:'quality_score')
        self.quality_score = attributes[:'quality_score']
      end

      if attributes.key?(:'competing_sources')
        self.competing_sources = attributes[:'competing_sources']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      time_to_invest_bucket_validator = EnumAttributeValidator.new('String', ["direct", "assisted", "delayed"])
      return false unless time_to_invest_bucket_validator.valid?(@time_to_invest_bucket)
      quality_score_validator = EnumAttributeValidator.new('String', ["high", "medium", "low", "suspicious"])
      return false unless quality_score_validator.valid?(@quality_score)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] time_to_invest_bucket Object to be assigned
    def time_to_invest_bucket=(time_to_invest_bucket)
      validator = EnumAttributeValidator.new('String', ["direct", "assisted", "delayed"])
      unless validator.valid?(time_to_invest_bucket)
        fail ArgumentError, "invalid value for \"time_to_invest_bucket\", must be one of #{validator.allowable_values}."
      end
      @time_to_invest_bucket = time_to_invest_bucket
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] quality_score Object to be assigned
    def quality_score=(quality_score)
      validator = EnumAttributeValidator.new('String', ["high", "medium", "low", "suspicious"])
      unless validator.valid?(quality_score)
        fail ArgumentError, "invalid value for \"quality_score\", must be one of #{validator.allowable_values}."
      end
      @quality_score = quality_score
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          utm_source == o.utm_source &&
          utm_campaign == o.utm_campaign &&
          utm_medium == o.utm_medium &&
          utm_content == o.utm_content &&
          clicked_at == o.clicked_at &&
          time_to_invest_bucket == o.time_to_invest_bucket &&
          quality_score == o.quality_score &&
          competing_sources == o.competing_sources
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [utm_source, utm_campaign, utm_medium, utm_content, clicked_at, time_to_invest_bucket, quality_score, competing_sources].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
