=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  class CompanyDisclosuresAttributes
    # The round whose Form C this is (`ofr_...`).
    attr_accessor :offering_id

    # ISO 4217 code, upper-case, of the round's own figures: `use_of_funds`, `prior_offerings`, `outstanding_notes`, `outstanding_debts` and `related_parties`. The round's currency — `USD` for a Reg CF round, `EUR` for an ECSP round. The financial statements, `ratios.revenue_per_employee` and `current_position` are in `financials_currency` instead.
    attr_accessor :currency

    # ISO 4217 code of the financial statements AND the founder's current-position figures (cash on hand, average monthly revenue, cost of goods, expenses) and `ratios.revenue_per_employee`. Falls back to `currency`. On the disclosures editor these fields share one denomination, which is this one. ISO 4217 code, upper-case, of the Form C `financial_statements` and of `ratios.revenue_per_employee`. The currency the issuer declared for its statements; equals `currency` unless the issuer declared another (a EUR round can file DKK, RON, GBP or USD statements).
    attr_accessor :financials_currency

    attr_accessor :filing

    attr_accessor :business

    attr_accessor :financial_statements

    attr_accessor :ratios

    attr_accessor :current_position

    # The issuer's financial-condition narrative, plain text.
    attr_accessor :financial_condition

    attr_accessor :financial_statement_documents

    # The contracts an investor signs (the page's \"Investment Terms\").
    attr_accessor :investment_documents

    # The issuer's risk factors, in the page's order, plain text.
    attr_accessor :risks

    # How the company says it will use the money at each amount raised.
    attr_accessor :use_of_funds

    attr_accessor :directors

    attr_accessor :officers

    # Holders of 20% or more of voting power, as disclosed.
    attr_accessor :voting_power

    attr_accessor :capital_structure

    # Exempt offerings in the prior three years, as disclosed.
    attr_accessor :prior_offerings

    attr_accessor :outstanding_notes

    attr_accessor :outstanding_debts

    attr_accessor :related_parties

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'offering_id' => :'offering_id',
        :'currency' => :'currency',
        :'financials_currency' => :'financials_currency',
        :'filing' => :'filing',
        :'business' => :'business',
        :'financial_statements' => :'financial_statements',
        :'ratios' => :'ratios',
        :'current_position' => :'current_position',
        :'financial_condition' => :'financial_condition',
        :'financial_statement_documents' => :'financial_statement_documents',
        :'investment_documents' => :'investment_documents',
        :'risks' => :'risks',
        :'use_of_funds' => :'use_of_funds',
        :'directors' => :'directors',
        :'officers' => :'officers',
        :'voting_power' => :'voting_power',
        :'capital_structure' => :'capital_structure',
        :'prior_offerings' => :'prior_offerings',
        :'outstanding_notes' => :'outstanding_notes',
        :'outstanding_debts' => :'outstanding_debts',
        :'related_parties' => :'related_parties'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'offering_id' => :'String',
        :'currency' => :'String',
        :'financials_currency' => :'String',
        :'filing' => :'CompanyDisclosuresAttributesFiling',
        :'business' => :'CompanyDisclosuresAttributesBusiness',
        :'financial_statements' => :'CompanyDisclosuresAttributesFinancialStatements',
        :'ratios' => :'CompanyDisclosuresAttributesRatios',
        :'current_position' => :'CompanyDisclosuresAttributesCurrentPosition',
        :'financial_condition' => :'String',
        :'financial_statement_documents' => :'Array<DisclosureDocument>',
        :'investment_documents' => :'Array<DisclosureDocument>',
        :'risks' => :'Array<String>',
        :'use_of_funds' => :'Array<CompanyDisclosuresAttributesUseOfFundsInner>',
        :'directors' => :'Array<DisclosurePerson>',
        :'officers' => :'Array<DisclosurePerson>',
        :'voting_power' => :'Array<CompanyDisclosuresAttributesVotingPowerInner>',
        :'capital_structure' => :'Array<CompanyDisclosuresAttributesCapitalStructureInner>',
        :'prior_offerings' => :'Array<CompanyDisclosuresAttributesPriorOfferingsInner>',
        :'outstanding_notes' => :'Array<CompanyDisclosuresAttributesOutstandingNotesInner>',
        :'outstanding_debts' => :'CompanyDisclosuresAttributesOutstandingDebts',
        :'related_parties' => :'CompanyDisclosuresAttributesRelatedParties'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'ratios',
        :'financial_condition',
        :'use_of_funds',
        :'directors',
        :'officers',
        :'voting_power',
        :'capital_structure',
        :'prior_offerings',
        :'outstanding_notes',
        :'outstanding_debts',
        :'related_parties'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::CompanyDisclosuresAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::CompanyDisclosuresAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'offering_id')
        self.offering_id = attributes[:'offering_id']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'financials_currency')
        self.financials_currency = attributes[:'financials_currency']
      end

      if attributes.key?(:'filing')
        self.filing = attributes[:'filing']
      end

      if attributes.key?(:'business')
        self.business = attributes[:'business']
      end

      if attributes.key?(:'financial_statements')
        self.financial_statements = attributes[:'financial_statements']
      end

      if attributes.key?(:'ratios')
        self.ratios = attributes[:'ratios']
      end

      if attributes.key?(:'current_position')
        self.current_position = attributes[:'current_position']
      end

      if attributes.key?(:'financial_condition')
        self.financial_condition = attributes[:'financial_condition']
      end

      if attributes.key?(:'financial_statement_documents')
        if (value = attributes[:'financial_statement_documents']).is_a?(Array)
          self.financial_statement_documents = value
        end
      end

      if attributes.key?(:'investment_documents')
        if (value = attributes[:'investment_documents']).is_a?(Array)
          self.investment_documents = value
        end
      end

      if attributes.key?(:'risks')
        if (value = attributes[:'risks']).is_a?(Array)
          self.risks = value
        end
      end

      if attributes.key?(:'use_of_funds')
        if (value = attributes[:'use_of_funds']).is_a?(Array)
          self.use_of_funds = value
        end
      end

      if attributes.key?(:'directors')
        if (value = attributes[:'directors']).is_a?(Array)
          self.directors = value
        end
      end

      if attributes.key?(:'officers')
        if (value = attributes[:'officers']).is_a?(Array)
          self.officers = value
        end
      end

      if attributes.key?(:'voting_power')
        if (value = attributes[:'voting_power']).is_a?(Array)
          self.voting_power = value
        end
      end

      if attributes.key?(:'capital_structure')
        if (value = attributes[:'capital_structure']).is_a?(Array)
          self.capital_structure = value
        end
      end

      if attributes.key?(:'prior_offerings')
        if (value = attributes[:'prior_offerings']).is_a?(Array)
          self.prior_offerings = value
        end
      end

      if attributes.key?(:'outstanding_notes')
        if (value = attributes[:'outstanding_notes']).is_a?(Array)
          self.outstanding_notes = value
        end
      end

      if attributes.key?(:'outstanding_debts')
        self.outstanding_debts = attributes[:'outstanding_debts']
      end

      if attributes.key?(:'related_parties')
        self.related_parties = attributes[:'related_parties']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          offering_id == o.offering_id &&
          currency == o.currency &&
          financials_currency == o.financials_currency &&
          filing == o.filing &&
          business == o.business &&
          financial_statements == o.financial_statements &&
          ratios == o.ratios &&
          current_position == o.current_position &&
          financial_condition == o.financial_condition &&
          financial_statement_documents == o.financial_statement_documents &&
          investment_documents == o.investment_documents &&
          risks == o.risks &&
          use_of_funds == o.use_of_funds &&
          directors == o.directors &&
          officers == o.officers &&
          voting_power == o.voting_power &&
          capital_structure == o.capital_structure &&
          prior_offerings == o.prior_offerings &&
          outstanding_notes == o.outstanding_notes &&
          outstanding_debts == o.outstanding_debts &&
          related_parties == o.related_parties
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [offering_id, currency, financials_currency, filing, business, financial_statements, ratios, current_position, financial_condition, financial_statement_documents, investment_documents, risks, use_of_funds, directors, officers, voting_power, capital_structure, prior_offerings, outstanding_notes, outstanding_debts, related_parties].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
