=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  # The record of one investment, or a tombstone (`visible: false`, only `id`). `visible` is founder visibility: a user's own canceled investment is a full record with `visible: false` and `status: canceled`. Investor PII keys are omitted without `read:investors:pii`, except on the user's own records. 
  class InvestmentDeltaRecord
    # Investment external id (`inv_…`), stable for the life of the investment.
    attr_accessor :id

    attr_accessor :visible

    # Company/offering audiences receive canceled and converted investments as tombstones; the values appear for audiences that can see them (e.g. the investor's own).
    attr_accessor :status

    attr_accessor :converted_to

    attr_accessor :converted_from

    # Offering external id (`ofr_…`).
    attr_accessor :offering

    # Company external id (`co_…`).
    attr_accessor :company

    attr_accessor :investment_type

    attr_accessor :offering_type

    # The founder dashboard's investment group label (e.g. CONFIRMED, IS READY).
    attr_accessor :group

    attr_accessor :applied_at

    attr_accessor :amounts

    # Shares this investment buys at its committed amount, as a decimal string (`\"295\"`, `\"1234.5\"`). For an investment through the SPV this is the company shares allotted to it through the vehicle. `null` when the round has no share concept (SAFE, note, reservation) or no shares are computed for the investment. Computed per investment; not the investor's post-funding position.
    attr_accessor :shares

    # Weighted average price per share for this investment (total share price / `shares`), as a decimal string. With tiered or early-bird pricing this need not equal any single price on the round. `null` whenever `shares` is `null`.
    attr_accessor :average_share_price

    attr_accessor :needs_whitelisting

    # PII scope.
    attr_accessor :external_username

    # PII scope.
    attr_accessor :message

    attr_accessor :investor

    attr_accessor :blockers

    attr_accessor :contracts

    # When this payload was observed by the publisher. Not a version.
    attr_accessor :observed_at

    # Ledger position of the change that listed this record (delta pages only).
    attr_accessor :cursor

    # Why the ledger row exists. `investor_deactivated` marks the first republish after the investor's account was deactivated (identity fields redacted). Delta pages only. 
    attr_accessor :reason

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'visible' => :'visible',
        :'status' => :'status',
        :'converted_to' => :'converted_to',
        :'converted_from' => :'converted_from',
        :'offering' => :'offering',
        :'company' => :'company',
        :'investment_type' => :'investment_type',
        :'offering_type' => :'offering_type',
        :'group' => :'group',
        :'applied_at' => :'applied_at',
        :'amounts' => :'amounts',
        :'shares' => :'shares',
        :'average_share_price' => :'average_share_price',
        :'needs_whitelisting' => :'needs_whitelisting',
        :'external_username' => :'external_username',
        :'message' => :'message',
        :'investor' => :'investor',
        :'blockers' => :'blockers',
        :'contracts' => :'contracts',
        :'observed_at' => :'observed_at',
        :'cursor' => :'cursor',
        :'reason' => :'reason'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'visible' => :'Boolean',
        :'status' => :'String',
        :'converted_to' => :'String',
        :'converted_from' => :'String',
        :'offering' => :'String',
        :'company' => :'String',
        :'investment_type' => :'String',
        :'offering_type' => :'String',
        :'group' => :'String',
        :'applied_at' => :'Time',
        :'amounts' => :'InvestmentDeltaRecordAmounts',
        :'shares' => :'String',
        :'average_share_price' => :'String',
        :'needs_whitelisting' => :'Boolean',
        :'external_username' => :'String',
        :'message' => :'String',
        :'investor' => :'InvestmentDeltaRecordInvestor',
        :'blockers' => :'Array<InvestmentDeltaRecordBlockersInner>',
        :'contracts' => :'Array<InvestmentDeltaRecordContractsInner>',
        :'observed_at' => :'Time',
        :'cursor' => :'String',
        :'reason' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'converted_to',
        :'converted_from',
        :'shares',
        :'average_share_price',
        :'external_username',
        :'message',
        :'cursor',
        :'reason'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::InvestmentDeltaRecord` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::InvestmentDeltaRecord`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'visible')
        self.visible = attributes[:'visible']
      else
        self.visible = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'converted_to')
        self.converted_to = attributes[:'converted_to']
      end

      if attributes.key?(:'converted_from')
        self.converted_from = attributes[:'converted_from']
      end

      if attributes.key?(:'offering')
        self.offering = attributes[:'offering']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'investment_type')
        self.investment_type = attributes[:'investment_type']
      end

      if attributes.key?(:'offering_type')
        self.offering_type = attributes[:'offering_type']
      end

      if attributes.key?(:'group')
        self.group = attributes[:'group']
      end

      if attributes.key?(:'applied_at')
        self.applied_at = attributes[:'applied_at']
      end

      if attributes.key?(:'amounts')
        self.amounts = attributes[:'amounts']
      end

      if attributes.key?(:'shares')
        self.shares = attributes[:'shares']
      end

      if attributes.key?(:'average_share_price')
        self.average_share_price = attributes[:'average_share_price']
      end

      if attributes.key?(:'needs_whitelisting')
        self.needs_whitelisting = attributes[:'needs_whitelisting']
      end

      if attributes.key?(:'external_username')
        self.external_username = attributes[:'external_username']
      end

      if attributes.key?(:'message')
        self.message = attributes[:'message']
      end

      if attributes.key?(:'investor')
        self.investor = attributes[:'investor']
      end

      if attributes.key?(:'blockers')
        if (value = attributes[:'blockers']).is_a?(Array)
          self.blockers = value
        end
      end

      if attributes.key?(:'contracts')
        if (value = attributes[:'contracts']).is_a?(Array)
          self.contracts = value
        end
      end

      if attributes.key?(:'observed_at')
        self.observed_at = attributes[:'observed_at']
      else
        self.observed_at = nil
      end

      if attributes.key?(:'cursor')
        self.cursor = attributes[:'cursor']
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @visible.nil?
        invalid_properties.push('invalid value for "visible", visible cannot be nil.')
      end

      if @observed_at.nil?
        invalid_properties.push('invalid value for "observed_at", observed_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @visible.nil?
      status_validator = EnumAttributeValidator.new('String', ["reserved", "active", "executed", "canceled", "converted"])
      return false unless status_validator.valid?(@status)
      return false if @observed_at.nil?
      reason_validator = EnumAttributeValidator.new('String', ["changed", "reprojected", "investor_deactivated"])
      return false unless reason_validator.valid?(@reason)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["reserved", "active", "executed", "canceled", "converted"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] reason Object to be assigned
    def reason=(reason)
      validator = EnumAttributeValidator.new('String', ["changed", "reprojected", "investor_deactivated"])
      unless validator.valid?(reason)
        fail ArgumentError, "invalid value for \"reason\", must be one of #{validator.allowable_values}."
      end
      @reason = reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          visible == o.visible &&
          status == o.status &&
          converted_to == o.converted_to &&
          converted_from == o.converted_from &&
          offering == o.offering &&
          company == o.company &&
          investment_type == o.investment_type &&
          offering_type == o.offering_type &&
          group == o.group &&
          applied_at == o.applied_at &&
          amounts == o.amounts &&
          shares == o.shares &&
          average_share_price == o.average_share_price &&
          needs_whitelisting == o.needs_whitelisting &&
          external_username == o.external_username &&
          message == o.message &&
          investor == o.investor &&
          blockers == o.blockers &&
          contracts == o.contracts &&
          observed_at == o.observed_at &&
          cursor == o.cursor &&
          reason == o.reason
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, visible, status, converted_to, converted_from, offering, company, investment_type, offering_type, group, applied_at, amounts, shares, average_share_price, needs_whitelisting, external_username, message, investor, blockers, contracts, observed_at, cursor, reason].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
