=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  # Either `email` (invite an unknown recipient) or `wefunder_user_id` (target an existing Wefunder user) should be provided. `spv_id` is required on `POST /partner/investment_sessions`; on the deprecated SPV-nested path the SPV comes from the URL instead. 
  class InvestmentSessionCreateInput
    # The SPV to invest into (prefixed, e.g. `spv_abc123`).
    attr_accessor :spv_id

    attr_accessor :email

    attr_accessor :wefunder_user_id

    # Fixed investment amount, in cents (whole dollars only). Locks the checkout to exactly this value, overriding the SPV's min/max purchase range. Omit to let the recipient choose an amount within that range. 
    attr_accessor :allocation_cents

    # Where to send the recipient after they complete the session.
    attr_accessor :success_url

    # Session lifetime in hours (default 720, i.e. 30 days).
    attr_accessor :expires_in_hours

    # Free-form key/value pairs stored with the session and echoed back on reads.
    attr_accessor :metadata

    # The Intent that gated the SPV's creation, for audit; stored in `metadata`.
    attr_accessor :intent_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'spv_id' => :'spv_id',
        :'email' => :'email',
        :'wefunder_user_id' => :'wefunder_user_id',
        :'allocation_cents' => :'allocation_cents',
        :'success_url' => :'success_url',
        :'expires_in_hours' => :'expires_in_hours',
        :'metadata' => :'metadata',
        :'intent_id' => :'intent_id'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'spv_id' => :'String',
        :'email' => :'String',
        :'wefunder_user_id' => :'String',
        :'allocation_cents' => :'Integer',
        :'success_url' => :'String',
        :'expires_in_hours' => :'Integer',
        :'metadata' => :'Object',
        :'intent_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'spv_id',
        :'email',
        :'wefunder_user_id',
        :'allocation_cents',
        :'success_url',
        :'expires_in_hours',
        :'metadata',
        :'intent_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::InvestmentSessionCreateInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::InvestmentSessionCreateInput`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'spv_id')
        self.spv_id = attributes[:'spv_id']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'wefunder_user_id')
        self.wefunder_user_id = attributes[:'wefunder_user_id']
      end

      if attributes.key?(:'allocation_cents')
        self.allocation_cents = attributes[:'allocation_cents']
      end

      if attributes.key?(:'success_url')
        self.success_url = attributes[:'success_url']
      end

      if attributes.key?(:'expires_in_hours')
        self.expires_in_hours = attributes[:'expires_in_hours']
      end

      if attributes.key?(:'metadata')
        self.metadata = attributes[:'metadata']
      end

      if attributes.key?(:'intent_id')
        self.intent_id = attributes[:'intent_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@allocation_cents.nil? && @allocation_cents < 100
        invalid_properties.push('invalid value for "allocation_cents", must be greater than or equal to 100.')
      end

      if !@expires_in_hours.nil? && @expires_in_hours > 2160
        invalid_properties.push('invalid value for "expires_in_hours", must be smaller than or equal to 2160.')
      end

      if !@expires_in_hours.nil? && @expires_in_hours < 1
        invalid_properties.push('invalid value for "expires_in_hours", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@allocation_cents.nil? && @allocation_cents < 100
      return false if !@expires_in_hours.nil? && @expires_in_hours > 2160
      return false if !@expires_in_hours.nil? && @expires_in_hours < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] allocation_cents Value to be assigned
    def allocation_cents=(allocation_cents)
      if !allocation_cents.nil? && allocation_cents < 100
        fail ArgumentError, 'invalid value for "allocation_cents", must be greater than or equal to 100.'
      end

      @allocation_cents = allocation_cents
    end

    # Custom attribute writer method with validation
    # @param [Object] expires_in_hours Value to be assigned
    def expires_in_hours=(expires_in_hours)
      if !expires_in_hours.nil? && expires_in_hours > 2160
        fail ArgumentError, 'invalid value for "expires_in_hours", must be smaller than or equal to 2160.'
      end

      if !expires_in_hours.nil? && expires_in_hours < 1
        fail ArgumentError, 'invalid value for "expires_in_hours", must be greater than or equal to 1.'
      end

      @expires_in_hours = expires_in_hours
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          spv_id == o.spv_id &&
          email == o.email &&
          wefunder_user_id == o.wefunder_user_id &&
          allocation_cents == o.allocation_cents &&
          success_url == o.success_url &&
          expires_in_hours == o.expires_in_hours &&
          metadata == o.metadata &&
          intent_id == o.intent_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [spv_id, email, wefunder_user_id, allocation_cents, success_url, expires_in_hours, metadata, intent_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
