=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  class PortfolioPositionAttributes
    attr_accessor :offering_id

    attr_accessor :company

    # `fund` for SPV and fund vehicles; the underlying companies appear in `holdings` where recorded.
    attr_accessor :asset_type

    # What the round issued, as `{ type, label }`. Null when the round has no security recorded.
    attr_accessor :security

    # `sold` means the stake was transferred away (secondary sale).
    attr_accessor :status

    # Why the position ended. Set only for `exited` and `failed` positions — a `sold` position ended with the transfer itself, and some older positions have no recorded ending. `ipo` means the company went public; distributions, if any, appear in `realized_gain_cents`. 
    attr_accessor :exit_reason

    attr_accessor :invested_at

    # ISO 4217 code, lower-case, of the investment amounts on this position and its `securities` (cost basis, values, gains, share price) — the offering's currency: `usd`, or `eur` for an ECSP round. A security's note cap and pre-money valuation carry their own `terms.currency`, which can differ.
    attr_accessor :currency

    attr_accessor :cost_basis_cents

    # Estimated current value; based on cost basis when no newer valuation has been recorded.
    attr_accessor :current_value_cents

    # Can be negative.
    attr_accessor :unrealized_gain_cents

    attr_accessor :realized_gain_cents

    # Decimal string. Null when cost basis is zero.
    attr_accessor :return_multiple

    attr_accessor :shares_held

    # Null when the position's securities carry different prices — see the per-entry values.
    attr_accessor :current_share_price

    attr_accessor :securities

    # Companies the vehicle invested in, for fund positions. Empty for non-fund positions and for vehicles without recorded holdings.
    attr_accessor :holdings

    # The number of distinct investors in this deal. Present on the syndicate endpoint only.
    attr_accessor :investor_count

    # When the values in this position were last calculated (the oldest timestamp when several underlying records are combined).
    attr_accessor :as_of

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'offering_id' => :'offering_id',
        :'company' => :'company',
        :'asset_type' => :'asset_type',
        :'security' => :'security',
        :'status' => :'status',
        :'exit_reason' => :'exit_reason',
        :'invested_at' => :'invested_at',
        :'currency' => :'currency',
        :'cost_basis_cents' => :'cost_basis_cents',
        :'current_value_cents' => :'current_value_cents',
        :'unrealized_gain_cents' => :'unrealized_gain_cents',
        :'realized_gain_cents' => :'realized_gain_cents',
        :'return_multiple' => :'return_multiple',
        :'shares_held' => :'shares_held',
        :'current_share_price' => :'current_share_price',
        :'securities' => :'securities',
        :'holdings' => :'holdings',
        :'investor_count' => :'investor_count',
        :'as_of' => :'as_of'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'offering_id' => :'String',
        :'company' => :'PortfolioCompanyRef',
        :'asset_type' => :'String',
        :'security' => :'SecuritySummary',
        :'status' => :'String',
        :'exit_reason' => :'String',
        :'invested_at' => :'Time',
        :'currency' => :'String',
        :'cost_basis_cents' => :'Integer',
        :'current_value_cents' => :'Integer',
        :'unrealized_gain_cents' => :'Integer',
        :'realized_gain_cents' => :'Integer',
        :'return_multiple' => :'String',
        :'shares_held' => :'String',
        :'current_share_price' => :'String',
        :'securities' => :'Array<PortfolioSecurity>',
        :'holdings' => :'Array<PortfolioHolding>',
        :'investor_count' => :'Integer',
        :'as_of' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'security',
        :'exit_reason',
        :'invested_at',
        :'return_multiple',
        :'shares_held',
        :'current_share_price',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::PortfolioPositionAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::PortfolioPositionAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'offering_id')
        self.offering_id = attributes[:'offering_id']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'asset_type')
        self.asset_type = attributes[:'asset_type']
      end

      if attributes.key?(:'security')
        self.security = attributes[:'security']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'exit_reason')
        self.exit_reason = attributes[:'exit_reason']
      end

      if attributes.key?(:'invested_at')
        self.invested_at = attributes[:'invested_at']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'cost_basis_cents')
        self.cost_basis_cents = attributes[:'cost_basis_cents']
      end

      if attributes.key?(:'current_value_cents')
        self.current_value_cents = attributes[:'current_value_cents']
      end

      if attributes.key?(:'unrealized_gain_cents')
        self.unrealized_gain_cents = attributes[:'unrealized_gain_cents']
      end

      if attributes.key?(:'realized_gain_cents')
        self.realized_gain_cents = attributes[:'realized_gain_cents']
      end

      if attributes.key?(:'return_multiple')
        self.return_multiple = attributes[:'return_multiple']
      end

      if attributes.key?(:'shares_held')
        self.shares_held = attributes[:'shares_held']
      end

      if attributes.key?(:'current_share_price')
        self.current_share_price = attributes[:'current_share_price']
      end

      if attributes.key?(:'securities')
        if (value = attributes[:'securities']).is_a?(Array)
          self.securities = value
        end
      end

      if attributes.key?(:'holdings')
        if (value = attributes[:'holdings']).is_a?(Array)
          self.holdings = value
        end
      end

      if attributes.key?(:'investor_count')
        self.investor_count = attributes[:'investor_count']
      end

      if attributes.key?(:'as_of')
        self.as_of = attributes[:'as_of']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      asset_type_validator = EnumAttributeValidator.new('String', ["company", "fund"])
      return false unless asset_type_validator.valid?(@asset_type)
      status_validator = EnumAttributeValidator.new('String', ["active", "exited", "sold", "failed"])
      return false unless status_validator.valid?(@status)
      exit_reason_validator = EnumAttributeValidator.new('String', ["ipo", "acquisition", "buyback", "failed", "winding_down"])
      return false unless exit_reason_validator.valid?(@exit_reason)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] asset_type Object to be assigned
    def asset_type=(asset_type)
      validator = EnumAttributeValidator.new('String', ["company", "fund"])
      unless validator.valid?(asset_type)
        fail ArgumentError, "invalid value for \"asset_type\", must be one of #{validator.allowable_values}."
      end
      @asset_type = asset_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "exited", "sold", "failed"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] exit_reason Object to be assigned
    def exit_reason=(exit_reason)
      validator = EnumAttributeValidator.new('String', ["ipo", "acquisition", "buyback", "failed", "winding_down"])
      unless validator.valid?(exit_reason)
        fail ArgumentError, "invalid value for \"exit_reason\", must be one of #{validator.allowable_values}."
      end
      @exit_reason = exit_reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          offering_id == o.offering_id &&
          company == o.company &&
          asset_type == o.asset_type &&
          security == o.security &&
          status == o.status &&
          exit_reason == o.exit_reason &&
          invested_at == o.invested_at &&
          currency == o.currency &&
          cost_basis_cents == o.cost_basis_cents &&
          current_value_cents == o.current_value_cents &&
          unrealized_gain_cents == o.unrealized_gain_cents &&
          realized_gain_cents == o.realized_gain_cents &&
          return_multiple == o.return_multiple &&
          shares_held == o.shares_held &&
          current_share_price == o.current_share_price &&
          securities == o.securities &&
          holdings == o.holdings &&
          investor_count == o.investor_count &&
          as_of == o.as_of
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [offering_id, company, asset_type, security, status, exit_reason, invested_at, currency, cost_basis_cents, current_value_cents, unrealized_gain_cents, realized_gain_cents, return_multiple, shares_held, current_share_price, securities, holdings, investor_count, as_of].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
