=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  class SyndicateDealAttributes
    attr_accessor :name

    # Where the round is in its life (same values as an offering's `status`).
    attr_accessor :status

    attr_accessor :company_name

    # Internal integer id. Deprecated — use `company` (`co_...`) instead.
    attr_accessor :company_id

    # The company's id (`co_...`).
    attr_accessor :company

    # Company slug/URL path
    attr_accessor :company_url

    # Company logo URL
    attr_accessor :company_logo_url

    # Amount raised in whole dollars, as a string
    attr_accessor :amount_raised

    # Count of distinct active investors
    attr_accessor :investor_count

    # Target funding amount in **cents**, as a string (the one cents field on this object)
    attr_accessor :funding_target

    attr_accessor :exemption

    attr_accessor :security

    # Minimum investment in whole dollars, as a string
    attr_accessor :min_investment

    # Maximum investment in whole dollars, as a string
    attr_accessor :max_investment

    # Deal funding purpose / description
    attr_accessor :description

    attr_accessor :created_at

    attr_accessor :updated_at

    # When the deal finished raising. Null while `status` is `upcoming` or `open`.
    attr_accessor :closed_at

    # ISO 8601 timestamp when funding opened
    attr_accessor :funding_started_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'status' => :'status',
        :'company_name' => :'company_name',
        :'company_id' => :'company_id',
        :'company' => :'company',
        :'company_url' => :'company_url',
        :'company_logo_url' => :'company_logo_url',
        :'amount_raised' => :'amount_raised',
        :'investor_count' => :'investor_count',
        :'funding_target' => :'funding_target',
        :'exemption' => :'exemption',
        :'security' => :'security',
        :'min_investment' => :'min_investment',
        :'max_investment' => :'max_investment',
        :'description' => :'description',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'closed_at' => :'closed_at',
        :'funding_started_at' => :'funding_started_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'status' => :'String',
        :'company_name' => :'String',
        :'company_id' => :'Integer',
        :'company' => :'String',
        :'company_url' => :'String',
        :'company_logo_url' => :'String',
        :'amount_raised' => :'String',
        :'investor_count' => :'Integer',
        :'funding_target' => :'String',
        :'exemption' => :'SyndicateDealAttributesExemption',
        :'security' => :'SyndicateDealAttributesSecurity',
        :'min_investment' => :'String',
        :'max_investment' => :'String',
        :'description' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'closed_at' => :'Time',
        :'funding_started_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'company',
        :'company_url',
        :'company_logo_url',
        :'amount_raised',
        :'funding_target',
        :'exemption',
        :'security',
        :'min_investment',
        :'max_investment',
        :'description',
        :'closed_at',
        :'funding_started_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::SyndicateDealAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::SyndicateDealAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'company_name')
        self.company_name = attributes[:'company_name']
      end

      if attributes.key?(:'company_id')
        self.company_id = attributes[:'company_id']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'company_url')
        self.company_url = attributes[:'company_url']
      end

      if attributes.key?(:'company_logo_url')
        self.company_logo_url = attributes[:'company_logo_url']
      end

      if attributes.key?(:'amount_raised')
        self.amount_raised = attributes[:'amount_raised']
      end

      if attributes.key?(:'investor_count')
        self.investor_count = attributes[:'investor_count']
      end

      if attributes.key?(:'funding_target')
        self.funding_target = attributes[:'funding_target']
      end

      if attributes.key?(:'exemption')
        self.exemption = attributes[:'exemption']
      end

      if attributes.key?(:'security')
        self.security = attributes[:'security']
      end

      if attributes.key?(:'min_investment')
        self.min_investment = attributes[:'min_investment']
      end

      if attributes.key?(:'max_investment')
        self.max_investment = attributes[:'max_investment']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end

      if attributes.key?(:'closed_at')
        self.closed_at = attributes[:'closed_at']
      end

      if attributes.key?(:'funding_started_at')
        self.funding_started_at = attributes[:'funding_started_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["upcoming", "open", "closed", "canceled"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["upcoming", "open", "closed", "canceled"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          status == o.status &&
          company_name == o.company_name &&
          company_id == o.company_id &&
          company == o.company &&
          company_url == o.company_url &&
          company_logo_url == o.company_logo_url &&
          amount_raised == o.amount_raised &&
          investor_count == o.investor_count &&
          funding_target == o.funding_target &&
          exemption == o.exemption &&
          security == o.security &&
          min_investment == o.min_investment &&
          max_investment == o.max_investment &&
          description == o.description &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          closed_at == o.closed_at &&
          funding_started_at == o.funding_started_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, status, company_name, company_id, company, company_url, company_logo_url, amount_raised, investor_count, funding_target, exemption, security, min_investment, max_investment, description, created_at, updated_at, closed_at, funding_started_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
