=begin
#Wefunder API v2

#OAuth 2.0 API for accessing Wefunder data programmatically.  ## Authentication  This API uses OAuth 2.0 for authentication. To get started:  1. Create an OAuth application at `/oauth/applications` 2. Get your Client ID and Client Secret 3. Implement the OAuth 2.0 Authorization Code flow 4. Use the access token to make API requests  ## Versioning  The API is versioned by the dated `Wefunder-Version` request header (`YYYY-MM-DD`), never by the URL. Resolution is header → your application's pinned version → latest; every response carries `Wefunder-Version` (the version that handled it) and `Wefunder-Version-Latest`. An unknown value returns `400 invalid_request` naming the valid versions. Current: `2026-10-01`.  ## Rate Limits  - Standard API: 1,000 requests/hour per token - Admin API: 10,000 requests/hour per token  ## Base URL  All API requests should be made to: `https://api.wefunder.com` (no version in the path). 

The version of the OpenAPI document: 2.0
Contact: api@wefunder.com
Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module WefunderGenerated
  class SyndicateAttributes
    attr_accessor :name

    attr_accessor :slug

    # Short description / tagline for the syndicate
    attr_accessor :tagline

    attr_accessor :description

    # Syndicate icon/avatar URL
    attr_accessor :avatar_url

    attr_accessor :published

    attr_accessor :launched

    # Whether the syndicate is accepting new members (nil defaults to true)
    attr_accessor :membership_open

    # How the syndicate invests (e.g. `annual_subscription`, `traditional_fund`); null for deal-by-deal syndicates.
    attr_accessor :syndicate_type

    # Whether accredited applicants are approved automatically.
    attr_accessor :auto_accept_accredited_members

    # Whether members must invest through the syndicate's fund.
    attr_accessor :fund_required

    attr_accessor :annual_subscription

    attr_accessor :traditional_fund

    attr_accessor :member_count

    # Number of live deals (the same set `GET /syndicates/{syndicate_id}/deals` returns)
    attr_accessor :deal_count

    # Internal integer id. Deprecated — use `primary_fund_company` (`co_...`) instead.
    attr_accessor :primary_fund_company_id

    # The primary fund company's id (`co_...`), when the syndicate has one.
    attr_accessor :primary_fund_company

    # Internal integer id. Deprecated — use `created_by` (`usr_...`) instead.
    attr_accessor :created_by_user_id

    # The creating user's id (`usr_...`).
    attr_accessor :created_by

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'slug' => :'slug',
        :'tagline' => :'tagline',
        :'description' => :'description',
        :'avatar_url' => :'avatar_url',
        :'published' => :'published',
        :'launched' => :'launched',
        :'membership_open' => :'membership_open',
        :'syndicate_type' => :'syndicate_type',
        :'auto_accept_accredited_members' => :'auto_accept_accredited_members',
        :'fund_required' => :'fund_required',
        :'annual_subscription' => :'annual_subscription',
        :'traditional_fund' => :'traditional_fund',
        :'member_count' => :'member_count',
        :'deal_count' => :'deal_count',
        :'primary_fund_company_id' => :'primary_fund_company_id',
        :'primary_fund_company' => :'primary_fund_company',
        :'created_by_user_id' => :'created_by_user_id',
        :'created_by' => :'created_by',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'slug' => :'String',
        :'tagline' => :'String',
        :'description' => :'String',
        :'avatar_url' => :'String',
        :'published' => :'Boolean',
        :'launched' => :'Boolean',
        :'membership_open' => :'Boolean',
        :'syndicate_type' => :'String',
        :'auto_accept_accredited_members' => :'Boolean',
        :'fund_required' => :'Boolean',
        :'annual_subscription' => :'SyndicateAttributesAnnualSubscription',
        :'traditional_fund' => :'SyndicateAttributesTraditionalFund',
        :'member_count' => :'Integer',
        :'deal_count' => :'Integer',
        :'primary_fund_company_id' => :'Integer',
        :'primary_fund_company' => :'String',
        :'created_by_user_id' => :'Integer',
        :'created_by' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tagline',
        :'description',
        :'avatar_url',
        :'syndicate_type',
        :'primary_fund_company_id',
        :'primary_fund_company',
        :'created_by',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WefunderGenerated::SyndicateAttributes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WefunderGenerated::SyndicateAttributes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      end

      if attributes.key?(:'tagline')
        self.tagline = attributes[:'tagline']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'avatar_url')
        self.avatar_url = attributes[:'avatar_url']
      end

      if attributes.key?(:'published')
        self.published = attributes[:'published']
      end

      if attributes.key?(:'launched')
        self.launched = attributes[:'launched']
      end

      if attributes.key?(:'membership_open')
        self.membership_open = attributes[:'membership_open']
      end

      if attributes.key?(:'syndicate_type')
        self.syndicate_type = attributes[:'syndicate_type']
      end

      if attributes.key?(:'auto_accept_accredited_members')
        self.auto_accept_accredited_members = attributes[:'auto_accept_accredited_members']
      end

      if attributes.key?(:'fund_required')
        self.fund_required = attributes[:'fund_required']
      end

      if attributes.key?(:'annual_subscription')
        self.annual_subscription = attributes[:'annual_subscription']
      end

      if attributes.key?(:'traditional_fund')
        self.traditional_fund = attributes[:'traditional_fund']
      end

      if attributes.key?(:'member_count')
        self.member_count = attributes[:'member_count']
      end

      if attributes.key?(:'deal_count')
        self.deal_count = attributes[:'deal_count']
      end

      if attributes.key?(:'primary_fund_company_id')
        self.primary_fund_company_id = attributes[:'primary_fund_company_id']
      end

      if attributes.key?(:'primary_fund_company')
        self.primary_fund_company = attributes[:'primary_fund_company']
      end

      if attributes.key?(:'created_by_user_id')
        self.created_by_user_id = attributes[:'created_by_user_id']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          slug == o.slug &&
          tagline == o.tagline &&
          description == o.description &&
          avatar_url == o.avatar_url &&
          published == o.published &&
          launched == o.launched &&
          membership_open == o.membership_open &&
          syndicate_type == o.syndicate_type &&
          auto_accept_accredited_members == o.auto_accept_accredited_members &&
          fund_required == o.fund_required &&
          annual_subscription == o.annual_subscription &&
          traditional_fund == o.traditional_fund &&
          member_count == o.member_count &&
          deal_count == o.deal_count &&
          primary_fund_company_id == o.primary_fund_company_id &&
          primary_fund_company == o.primary_fund_company &&
          created_by_user_id == o.created_by_user_id &&
          created_by == o.created_by &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, slug, tagline, description, avatar_url, published, launched, membership_open, syndicate_type, auto_accept_accredited_members, fund_required, annual_subscription, traditional_fund, member_count, deal_count, primary_fund_company_id, primary_fund_company, created_by_user_id, created_by, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WefunderGenerated.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
